---
- hosts: all
  become: yes
  become_user: ubuntu
  tasks:
    - name: Run kubernetes deployment command.
      command: kubectl apply --kubeconfig /home/ubuntu/admin.conf -f /home/ubuntu/deployment.yml
      args:
        chdir: /home/ubuntu
    - name: Set KUBECONFIG.
      command:  export KUBECONFIG=/home/ubuntu/admin.conf    
    - name: Display deployment details.
      command: kubectl get deployments --kubeconfig /home/ubuntu/admin.conf
    - name: Display service details.
      command: kubectl get svc --kubeconfig /home/ubuntu/admin.conf
