---
- hosts: all
  become: yes
  become_user: ubuntu
  tasks:
    - name: Run kubernetes deployment command.
      command: kubectl apply --kubeconfig /home/ubuntu/admin.conf -f /home/ubuntu/deployment.yml
      args:
        chdir: /home/ubuntu
    - name: Sleep 10 seconds
      command:  sleep 10
    - name: Display deployment details.
      command: kubectl get deployments --kubeconfig /home/ubuntu/admin.conf
    - name: Display service details.
      command: kubectl get svc --kubeconfig /home/ubuntu/admin.conf
    - name: Configuring Prometheus
      script: /home/ubuntu/e2epipeline/monitoring/prometheus.sh
    - name: Configuring Grafana
      script: /home/ubuntu/e2epipeline/monitoring/grafana.sh
    - name: Configuring Kube State Metrics
      script: /home/ubuntu/e2epipeline/monitoring/metrics.sh  
