---
- hosts: all
  become: yes
  become_user: ubuntu
  tasks:
    - name: Install Git
      yum:
        name: git
        state: present
    - name: Fetch deployment files from Git hub
      git:
        repo: https://github.com/kishorsg/e2epipeline.git
        dest: /home/ubuntu/
    - name: Run kubernetes deployment command.
      command: kubectl apply --kubeconfig /home/ubuntu/admin.conf -f /home/ubuntu/e2epipeline/deployment.yml
      args:
        chdir: /home/ubuntu/e2epipeline
    - name: Delete git repo folder
      command: rm -rf /home/ubuntu/e2epipeline 
